# Generated by Django 4.0.3 on 2022-03-12 23:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_eleitoral', models.CharField(max_length=12)),
                ('nome', models.CharField(max_length=150)),
                ('foto_usuario', models.ImageField(blank=True, upload_to='figuras/%Y-%m-%d')),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chamado', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('patrimonio', models.CharField(blank=True, max_length=10)),
                ('ip', models.CharField(blank=True, max_length=15)),
                ('prioridade', models.CharField(default='Normal', max_length=10)),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('figura_chamado', models.ImageField(blank=True, upload_to='figuras/%Y-%m-%d')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.categoria')),
                ('estado', models.ForeignKey(default='ABERTO', on_delete=django.db.models.deletion.CASCADE, to='chamados.estado')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.fila')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.usuario')),
            ],
        ),
    ]
