# Generated by Django 4.0.3 on 2022-03-13 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_prioridade_alter_chamado_prioridade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='titulo_eleitoral',
        ),
        migrations.AlterField(
            model_name='chamado',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.estado'),
        ),
    ]
