# Generated by Django 4.0.3 on 2022-03-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_remove_usuario_titulo_eleitoral_alter_chamado_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto_usuario',
        ),
    ]
