# Generated by Django 4.0.3 on 2022-03-19 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_remove_usuario_foto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chamados.categoria'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chamados.estado'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='fila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chamados.fila'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chamados.prioridade'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chamados.usuario'),
        ),
    ]
